[View in Colaboratory](https://colab.research.google.com/github/Masum06/gender_newspaper/blob/master/word2vec_diff.ipynb)

**Description**



*   Many kind of operations with Gensim word2vec model
*   Playing with word2vec
*   Comparison between 2 models



In [0]:
ls

datalab/


In [0]:
!pip install lxml

In [0]:
!pip install gensim

    100% |████████████████████████████████| 23.5MB 1.7MB/s 
    100% |████████████████████████████████| 1.4MB 12.5MB/s 
    100% |████████████████████████████████| 133kB 22.3MB/s 
    100% |████████████████████████████████| 61kB 19.3MB/s 
    100% |████████████████████████████████| 4.4MB 6.5MB/s 
    100% |████████████████████████████████| 552kB 20.8MB/s 
  Running setup.py bdist_wheel for smart-open ... - done
  Stored in directory: /content/.cache/pip/wheels/73/f1/9b/ccf93d4ba073b6f79b1ed9df68ab5ce048d8136d0efcf90b30
  Running setup.py bdist_wheel for bz2file ... - done
  Stored in directory: /content/.cache/pip/wheels/81/75/d6/e1317bf09bf1af5a30befc2a007869fa6e1f516b8f7c591cb9
Successfully built smart-open bz2file


###Load Trained Models

In [0]:
%%bash
git clone https://github.com/jeroenmeulenaar/python3-mega.git python3mega
cd python3mega
pip install -r requirements.txt

  Running setup.py bdist_wheel for URLObject: started
  Running setup.py bdist_wheel for URLObject: finished with status 'done'
  Stored in directory: /content/.cache/pip/wheels/fd/7e/18/ccb55ecc2834f945b769c1ff1df12ca5a14400ccfc58e3c515
  Running setup.py bdist_wheel for pycrypto: started
  Running setup.py bdist_wheel for pycrypto: finished with status 'done'
  Stored in directory: /content/.cache/pip/wheels/27/02/5e/77a69d0c16bb63c6ed32f5386f33a2809c94bd5414a2f6c196
Successfully built URLObject pycrypto


Cloning into 'python3mega'...


In [0]:
import os
os.chdir("python3mega")
from mega import Mega
m = Mega.from_ephemeral()
os.chdir("..")

In [0]:
m.download_from_url('https://mega.nz/#!1BJ1iYKZ!05H-DDnvzcfN4btuCF3ThExeG5T1xKvjzkOm2U6x5Uk')

In [0]:
m.download_from_url('https://mega.nz/#!MdYlBYRQ!qav9Yh_gjnhwiHonVYwfe_qq6rLZCglCbuA5AlFqX6U')

In [0]:
ls

datalab/  model_news_db_1  model_news_db_2  python3mega/


###Playing with model

In [0]:
len(model)

TypeError: ignored

In [0]:
model.wv.most_similar("entrepreneur")

[('economist', 0.902117133140564),
 ('architect', 0.900246262550354),
 ('activist', 0.8866156339645386),
 ('anthropologist', 0.8654515147209167),
 ('artist', 0.8624669313430786),
 ('astronaut', 0.8581064939498901),
 ('expert', 0.8556488752365112),
 ('actor', 0.8503183126449585),
 ('atheist', 0.8391861915588379),
 ('impostor', 0.8351146578788757)]

In [0]:
type(model)

gensim.models.word2vec.Word2Vec

In [0]:
minus_model = model - model
# NOT SUPPORTED

TypeError: ignored

In [0]:
type(model["entrepreneur"])
# numpy.ndarray

NameError: ignored

In [0]:
model["entrepreneur"]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.20235166,  0.53796643, -0.07205287, -0.4917733 , -0.18315537,
        0.44496745,  0.08833359, -0.21318987,  0.11201645,  0.43335387,
       -0.1899689 , -0.42741352, -0.12580433, -0.58701867,  0.23723133,
       -0.2702044 , -0.44369557, -0.1932195 ,  0.35374677, -0.11754068,
       -0.6376186 , -0.39672828, -0.08301786, -0.01188317,  0.37585056,
       -0.2097196 ,  0.01382275, -0.11978568, -0.1440628 ,  0.00935103,
        0.5103125 , -0.22633967, -0.00617537,  0.43256795,  0.06657786,
        0.46839565,  0.2057064 ,  0.03313362,  0.22063555, -0.10881404,
       -0.16358085, -0.832392  , -0.5055351 ,  0.17539665, -0.09579752,
        0.16052523,  0.13410763, -0.7746147 , -0.36171466,  0.1506706 ,
       -0.00747181, -0.50304437, -0.31410804, -0.22962591, -0.70568955,
        0.32004496, -0.2550136 , -0.7883951 ,  0.1766998 , -0.60241157,
        0.05927536,  0.14790818, -0.4264756 , -0.33307618, -0.2593861 ,
       -0.15762675,  0.0022651 , -0.1491662 ,  0.20896941, -0.17

In [0]:
model["entrepreneur"] = model["entrepreneur"] - model["entrepreneur"]
# NOT SUPPORTED

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


TypeError: ignored

In [0]:
model['boy']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.53867334, -0.361385  , -0.86674654, -0.17131948,  0.98401344,
        0.8067845 ,  0.1111766 , -0.01106134, -0.56461835,  1.3948219 ,
        1.6091311 ,  0.88039017, -0.7051991 , -0.2688786 , -0.41667518,
       -0.04546946, -0.48960957, -0.65181327,  0.12261411, -0.49630257,
        0.9350181 ,  0.8128392 ,  0.4655204 ,  1.6427513 ,  1.1391753 ,
       -0.8352595 , -0.75343394,  0.8382971 ,  1.9420936 , -0.48434746,
       -0.1996124 ,  1.2369007 , -0.1574192 ,  0.5786293 , -0.38559145,
        1.0986748 ,  0.70707583,  0.17745115,  1.5451361 ,  1.2911285 ,
       -1.5712801 ,  0.03593261,  0.74058783, -0.46568307, -1.5376679 ,
        0.64817244, -0.20519069,  0.19935532,  0.5433881 , -0.5299435 ,
       -1.8901308 ,  0.19142722,  0.01346795,  0.89286166,  1.1135262 ,
       -0.9282615 , -0.17957479,  1.0986031 , -0.52507997, -1.415834  ,
        0.08894284,  0.12335753, -0.4992399 , -1.046179  , -1.4660685 ,
       -1.7220666 , -0.00293653, -0.39979893, -1.7703484 ,  1.17

In [0]:
model.wv.syn0[model.wv.vocab['boy'].index] += 10

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


In [0]:
model['boy']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([10.538673 ,  9.638615 ,  9.133253 ,  9.82868  , 10.984014 ,
       10.806785 , 10.1111765,  9.988938 ,  9.435382 , 11.394822 ,
       11.609131 , 10.88039  ,  9.294801 ,  9.731121 ,  9.583324 ,
        9.954531 ,  9.51039  ,  9.3481865, 10.122614 ,  9.503697 ,
       10.935019 , 10.8128395, 10.465521 , 11.642752 , 11.139175 ,
        9.164741 ,  9.246566 , 10.838297 , 11.942094 ,  9.515653 ,
        9.800387 , 11.2369   ,  9.842581 , 10.5786295,  9.6144085,
       11.098675 , 10.707076 , 10.177451 , 11.545136 , 11.291128 ,
        8.4287195, 10.035933 , 10.740588 ,  9.534317 ,  8.462332 ,
       10.648172 ,  9.794809 , 10.199355 , 10.543388 ,  9.470057 ,
        8.109869 , 10.191427 , 10.013468 , 10.892861 , 11.113526 ,
        9.071738 ,  9.820425 , 11.098603 ,  9.47492  ,  8.584166 ,
       10.088943 , 10.123358 ,  9.50076  ,  8.953821 ,  8.533932 ,
        8.277933 ,  9.997064 ,  9.600201 ,  8.229651 , 11.17574  ,
       10.861771 , 10.41592  ,  9.177724 , 10.107386 , 10.6421

In [0]:
type(model1.wv.vocab)

dict

In [0]:
len(model1.wv.vocab)

94734

In [0]:
model1.wv.vocab["boy"]

In [0]:
for key in model.wv.vocab:
  print(key, end=" ")

here are two reasons companies fail they only do more of the same or what s new to me real solution quality growth is figuring out balance between activities exploration and exploitation both necessary but it can be too much a good thing consider facit i m actually old enough remember them was fantastic company were born deep in swedish forest made best mechanical calculators world everybody used did when electronic calculator came along continued doing exactly six months went from maximum revenue gone irony about story hearing engineers who had bought cheap small japan that double check their go wild few years back worked closely alongside european biotech let call brilliant applications promised diagnose even cure certain forms blood cancer every day creating something extremely innovative mantra we get right want perfect sad before became obsolete first heard 15 ago as visiting scholar at stanford university founder idea jim march power its coming up with search discovery products i

shoveling slice polished optical reactor induced fission decay marked uranium poorly regarded dates laser analyze thorium fossils animation illustrate ancient feedbacks ryan mixing drake strongest oceans forth antarctic surprising dating migrated illustration stops intermediate indeed slide garden sail gmo saving agricultural runoff toxic nutrition discussion apple eaten picked eleven grocery storage documented workers ninety antioxidants ball sugar missing weird empowered questioned democratic californian mexican picks slave traces planes automobiles production digitize particles reconstitute quotes inspire japanese farming fukushima headed tokyo contaminated import eighty shareholder farmer utilities suicides uncomfortable tractor combine bath depot hacking silly dance attached killed relationships language knock electronics historically produced roots monthly harvest cafeteria retail salad bags processing ripping tongue eat lettuce 6 hyper sweet reaction taste physiology conceived f

plaster upwards liz lagos waterways infested invasive aquatic weed livelihoods trading yields inflated hyacinth botanical niger delta southwestern yoruba gossip reproduction kp oma shortly relocated conviction mainland arresting boats mats restrictions whereby cleared impacted woven deployed requirement mega thirdly weave directed basket weaving pens thereby durable resilient killer ya du j w provider michael makoko poems thy brush thee thou activist pauses poet william blake regenerated algorithmically gut roar bark exhausted weary sodas pearls turing 1950 benjamin bot yourselves fool fooled readers flags ribbons wounded deer flag ecstasy brake whoa gertrude stein rkcp kurzweil believer analyzes emily dickinson fools boundaries philosophical devised provocation constitutes unstable constructed reflects intelligent wide existential reflection crops resurrection resurrect 48 bulk consideration dai rainfall preferably easiest actively metabolizing comprised behavioral 95 periods attracti

ratios withdraw liquidity narrower boosting marilyn philanthropic 94 coaching geology settling circling surrounds methane formaldehyde frail fallow elon musk infused cocaine browser onion naval browse censorship blower pirated fringes narcotics res crypto vendor pseudonym buyer allegiance vendors attentive frees marijuana encrypted posh reckoning purity censor payment flaw payments purchasing wallet administrator tumbling recipients laundering colombian opted consistently revelations snowden messaging unused extraterrestrial den uniform hesitation consciously seeks groundbreaking heforshe inviting counted pune mobilizing madam 180 electoral nato eu iceland goodwill emma impressions associations delusion widening northeast mountaintop glare exaggeration webb consortium gmt mirrors dwarfs comprise statue housed copernicus buckets bucket icy earths province spectra newest smithsonian carnegie furnace tucked bumps millionth ow coin simulated cluster leveled blasted wendy alma complementary

 humid diaspora apathetic ballot taxation facto mcluhan stacking persuading disagreement affords commenting manipulated playboy finland partake unlocking judging airtime nagging thighs converge reversal managerial illustrating diffuse prestige equilibrium steeply fifths bankruptcy unusually postwar deregulation endowments rankings registry redistribute concerts fluke stimulated invisibly layout arithmetic turquoise ghettos backpacks navigating riddled elam hurricanes georges mitch cuban bolted enrollment chan gar funa med grads rotations midwives haitian strengthening accredited percentages manifests rated acumen communicators emphasizing assertive unexamined succession reactors washer rags latrines emptied flush reused squatter pleasurable drum professionalized prefabricated proliferate shenzhen colombo grasping rider assessed defibrillator remembrance perished photojournalist jeep mohammed pigeons bathtub tel aviv pies inscriptions password dashboard telltale stakeholder advisory emi

In [0]:
type(model.wv.syn0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


numpy.ndarray

In [0]:
model.wv.syn0.shape

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


(21444, 100)

### Operation with models

In [0]:
model2 = Word2Vec(sentences=sentences_ted, size=100, window=5, min_count=5, workers=4, sg=0)

In [0]:
model.wv.syn0[model.wv.vocab['girl'].index]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


array([ 0.68554425,  0.10157108, -0.7449454 , -0.24022916,  0.5441695 ,
        0.610383  , -0.20478608, -0.28613013,  0.01091533,  1.9975687 ,
        2.186959  ,  0.71507174, -1.3840693 , -0.5798922 , -0.73626065,
        0.05398396, -0.6080174 , -0.89196277, -0.20498388, -0.08830798,
        1.8380361 ,  0.7997554 ,  0.80265677,  1.2184932 ,  0.9914013 ,
       -0.5328405 , -1.5946094 ,  0.70062786,  2.1661685 , -0.7763247 ,
       -0.02111788,  1.2333499 , -0.04017907,  0.68666005, -0.8404691 ,
        0.8378871 ,  1.3610681 ,  0.2582959 ,  1.7071942 ,  1.8665423 ,
       -1.8624346 ,  0.2010817 ,  1.0139104 ,  0.06464671, -2.0761201 ,
        0.61766857, -0.45810017,  0.6618068 ,  0.8667535 , -0.581396  ,
       -2.5663757 , -0.17998584,  0.11594088,  1.0170196 ,  1.5246077 ,
       -0.86083686, -0.6543994 ,  1.6371385 , -1.677256  , -2.0057821 ,
        0.05091102,  0.02741045, -1.3440304 , -1.2876939 , -1.4983475 ,
       -2.3604245 ,  0.581793  , -0.64178944, -2.0869982 ,  0.92

In [0]:
model2.wv.syn0[model2.wv.vocab['girl'].index]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


array([ 0.73765516,  0.14410049, -1.5159734 ,  0.11026169, -0.36297452,
        0.8716696 , -0.5489038 , -0.6679041 , -1.0622243 ,  1.8582126 ,
        1.6077975 ,  0.59419405, -1.4578733 , -0.33425564, -0.46074915,
       -1.2662373 , -0.8607062 , -0.81939465, -0.3693235 , -0.68424463,
        0.7406587 ,  1.0476669 ,  0.6308879 ,  1.5753742 ,  0.42115074,
       -0.44284433, -0.98523235,  0.6673049 ,  2.430775  , -0.5298175 ,
       -0.27842575,  0.82246333,  0.36350924,  0.7610863 , -0.22944477,
        0.76905406,  1.8934758 ,  0.09810046,  2.3696966 ,  1.5012349 ,
       -1.8743044 , -0.48837948,  1.3475703 ,  0.07082885, -1.3105445 ,
        1.098289  , -0.39137998,  0.43321988,  0.78511906,  0.66490215,
       -2.0185492 ,  0.9107035 ,  0.5364828 ,  0.20638907,  0.6617599 ,
       -0.85498923, -0.7027098 ,  1.2930545 , -0.8082383 , -1.8763634 ,
       -0.36142313,  0.23691738, -1.3211718 , -1.0809972 , -2.2425928 ,
       -1.670221  ,  0.5504213 , -1.6773217 , -3.0626001 ,  0.69

In [0]:
np.linalg.norm(model.wv.syn0[model.wv.vocab['criminal'].index])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


3.850182

In [0]:
np.linalg.norm(model2.wv.syn0[model2.wv.vocab['criminal'].index])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


3.660497

In [0]:
model.wv.most_similar("entrepreneur")

[('economist', 0.9144308567047119),
 ('architect', 0.890481173992157),
 ('expert', 0.8789657354354858),
 ('artist', 0.8719332218170166),
 ('activist', 0.8713411092758179),
 ('actor', 0.8620400428771973),
 ('anthropologist', 0.8516318798065186),
 ('astronaut', 0.8507596254348755),
 ('ecologist', 0.8371546864509583),
 ('illustrator', 0.8331782817840576)]

In [0]:
model2.wv.most_similar("entrepreneur")

NameError: ignored

In [0]:
model1.wv.vocab['criminal'].index

1294

In [0]:
model2.wv.vocab['criminal'].index

1294

In [0]:
model.wv.syn0[21443]
# This is the maximum allowed value

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


array([-0.05015383, -0.08498254,  0.05235778, -0.04854964, -0.015863  ,
       -0.03084175, -0.0532398 , -0.05302369, -0.06664182,  0.04560589,
       -0.02655116,  0.01601149, -0.01822092, -0.0444553 , -0.02158207,
       -0.02762219, -0.08780076, -0.02915213,  0.0127841 ,  0.00738108,
        0.04217616,  0.00426234, -0.06175462,  0.01681743,  0.05076963,
       -0.02654306, -0.01423969,  0.01933438,  0.04995146, -0.04988679,
        0.0391355 , -0.01248724, -0.08148462,  0.03214028,  0.03273794,
        0.0320871 ,  0.03226285, -0.00722395, -0.01789135,  0.07060676,
       -0.05129545,  0.11325247, -0.01455603,  0.00521235, -0.06996699,
        0.00426558,  0.02014294,  0.07392461, -0.00199707,  0.01694367,
       -0.04544626,  0.04083609,  0.02895463,  0.08205143, -0.03219597,
       -0.1301134 ,  0.02164999,  0.03522764, -0.09036277, -0.00527601,
        0.00352071, -0.04686397, -0.01771873, -0.07137675,  0.08342939,
       -0.00651247, -0.05287651,  0.07652795, -0.01051889, -0.05

In [0]:
vector_minus = model.wv.syn0[model.wv.vocab['girl'].index] - model2.wv.syn0[model.wv.vocab['girl'].index]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


In [0]:
print(vector_minus)

[-0.05211091 -0.0425294   0.77102804 -0.35049084  0.907144   -0.26128662
  0.34411776  0.38177395  1.0731395   0.13935614  0.5791615   0.12087768
  0.07380402 -0.24563658 -0.2755115   1.3202212   0.25268883 -0.07256812
  0.16433962  0.59593666  1.0973773  -0.24791151  0.17176884 -0.35688102
  0.5702506  -0.08999616 -0.609377    0.03332299 -0.26460648 -0.24650717
  0.2573079   0.4108866  -0.4036883  -0.07442623 -0.6110244   0.06883305
 -0.53240764  0.16019544 -0.6625024   0.36530745  0.01186979  0.6894612
 -0.3336599  -0.00618214 -0.76557565 -0.48062044 -0.06672019  0.22858694
  0.08163446 -1.2462981  -0.5478265  -1.0906893  -0.42054194  0.81063056
  0.86284775 -0.00584763  0.0483104   0.34408402 -0.86901766 -0.12941873
  0.41233414 -0.20950693 -0.02285862 -0.20669663  0.7442453  -0.69020355
  0.03137171  1.0355322   0.9756019   0.2331537   0.3657611  -0.7374347
 -0.47129327 -0.35739124  0.08417451  0.24699259 -0.91074264  0.36794433
 -0.64432317 -0.36735833 -0.22901171 -0.4092787  -0.4

###Load 2 models

In [0]:
import gensim
model1 = gensim.models.Word2Vec.load('model_news_db_1')
model2 = gensim.models.Word2Vec.load('model_news_db_2')

###Averaging model

In [0]:
print(model1.wv.similarity('woman', 'man'))
print(model2.wv.similarity('woman', 'man'))

0.8149608
0.80947113


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [0]:
print(model1.wv.similarity('king', 'man'))
print(model2.wv.similarity('king', 'man'))

0.37222734
0.36654928


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [0]:
print(model1.wv.most_similar(positive=['woman', 'king'], negative=['man']))
print(model2.wv.most_similar(positive=['woman', 'king'], negative=['man']))

[('queen', 0.7843930721282959), ('princess', 0.7201079726219177), ('monarch', 0.7111756801605225), ('diana', 0.6300253868103027), ('mary', 0.6259266138076782), ('kate', 0.6216628551483154), ('bhumibol', 0.6192911863327026), ('namgyel', 0.6127697825431824), ('widow', 0.6103571653366089), ('duchess', 0.6046750545501709)]
[('queen', 0.7829289436340332), ('princess', 0.6930142641067505), ('monarch', 0.6814134120941162), ('khesar', 0.6415609121322632), ('namgyel', 0.6375528573989868), ('prince', 0.6156015396118164), ('wangchuck', 0.6084578037261963), ('jigme', 0.6076049208641052), ('bhumibol', 0.5998407602310181), ('isabella', 0.5920835733413696)]


In [0]:
print(model1["man"])
print(model2["man"])

[ 2.3198788   0.400843   -0.03929096 -0.6279333   1.1569449  -1.2520182
 -1.359983   -0.9470723  -1.5585922   0.09702303  1.8668631  -1.4247651
 -0.7800773  -1.240886   -0.69002897 -2.2049456   2.9670684   0.16707467
  0.8848694  -0.48999318 -1.384563    2.397162    0.6544173  -1.9608128
 -3.2174747   2.1778908  -1.0785154  -1.9822384   2.6534054  -5.188941
  3.1948211   2.4518948  -0.81372774  0.786047   -2.3303332   1.6967942
  1.9556531   0.89204526  1.0865344  -1.6711987  -0.9583186  -1.4943813
 -2.5931826   1.9311044   0.8596744   1.7900788   0.7849783  -1.5823746
  3.3803468  -1.8924223   0.28102684 -1.4396254   2.6475792  -2.3221188
  0.4525161  -2.764021   -0.14103265  0.0254827  -1.7817127   0.8645506
 -2.326711   -0.50943255 -0.25100258  0.16618207 -2.933973    2.2813473
 -0.3798859   1.5654733   0.15153372 -1.656636    1.8206255   0.27548453
  2.9421272  -1.3034116  -0.51713365 -3.9172578  -0.93647844  4.2345743
  2.4402118   1.5918672   1.0615789  -0.197628   -4.010386    1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [0]:
print(np.linalg.norm(model1["woman"]))
print(np.linalg.norm(model2["woman"]))

18.27925
18.388672


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [0]:
model1_man = model1["man"]
model2_man = model2["man"]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [0]:
type(model1_man)

numpy.ndarray

In [0]:
from numpy import dot
from numpy.linalg import norm

c = dot(model1_man, model2_man)/norm(model1_man)/norm(model2_man)

In [0]:
print(c)

0.59380525


In [0]:
vec1 = model1["bnp"]
vec2 = model2["bnp"]

print(dot(vec1, vec2)/norm(vec1)/norm(vec2))

0.7541186


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


###Creating reverse map

In [0]:
index2word = {}
for key in model1.wv.vocab:
  index = model1.wv.vocab[key].index
  index2word[index] = key

In [0]:
index2word[94733]

'shanmuganathan'

In [0]:
len(index2word)

94734

###Creating similarity matrix

In [0]:
from numpy import dot
from numpy.linalg import norm

def similarity(model, index1, index2):
  vector1 = model.wv.syn0[index1]
  vector2 = model.wv.syn0[index2]
  c = dot(vector1, vector2)/norm(vector1)/norm(vector2)
  return c

In [0]:
similarity(model1, 0, 1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


0.38910252

In [0]:
size = len(model1.wv.syn0)
print(size)

94734


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


In [0]:
#size = 94734

In [0]:
import numpy as np
similarity_matrix1 = np.zeros(size, dtype="float")
similarity_matrix2 = np.zeros(size, dtype="float")

In [0]:
for i in range(size):
  if i%1000 == 0:
    print("index: ",i)
  for j in range(size):
    similarity_matrix1[i] += similarity(model1, i,j)
    similarity_matrix2[i] += similarity(model2, i,j)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


In [0]:
np.save("similarity_matrix1", similarity_matrix1)
np.save("similarity_matrix2", similarity_matrix2)

In [0]:
similarity_diff = similarity_matrix1 - similarity_matrix2

In [0]:
similarity_fract = similarity_matrix1 / similarity_matrix2

###Save Model

In [0]:
MODEL_DIR = 'emb_newsdb2/'
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)
model2.save(os.path.join(MODEL_DIR,'word2vec'))